// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "CANTalon.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<CANTalon> RobotMap::intakeTreadMotor;
std::shared_ptr<CANTalon> RobotMap::intakeShooterMotor;
std::shared_ptr<SpeedController> RobotMap::driveTrainRightFront;
std::shared_ptr<SpeedController> RobotMap::driveTrainRightBack;
std::shared_ptr<SpeedController> RobotMap::driveTrainLeftFront;
std::shared_ptr<SpeedController> RobotMap::driveTrainLeftBack;
std::shared_ptr<RobotDrive> RobotMap::driveTrainRobotDrive41;
std::shared_ptr<CANTalon> RobotMap::flapperFlapperMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    intakeTreadMotor.reset(new CANTalon(17));
    lw->AddActuator("Intake", "TreadMotor", intakeTreadMotor);
    
    intakeShooterMotor.reset(new CANTalon(13));
    lw->AddActuator("Intake", "ShooterMotor", intakeShooterMotor);
    
    driveTrainRightFront.reset(new TalonSRX(0));
    lw->AddActuator("DriveTrain", "RightFront", std::static_pointer_cast<TalonSRX>(driveTrainRightFront));
    
    driveTrainRightBack.reset(new TalonSRX(1));
    lw->AddActuator("DriveTrain", "RightBack", std::static_pointer_cast<TalonSRX>(driveTrainRightBack));
    
    driveTrainLeftFront.reset(new TalonSRX(2));
    lw->AddActuator("DriveTrain", "LeftFront", std::static_pointer_cast<TalonSRX>(driveTrainLeftFront));
    
    driveTrainLeftBack.reset(new TalonSRX(3));
    lw->AddActuator("DriveTrain", "LeftBack", std::static_pointer_cast<TalonSRX>(driveTrainLeftBack));
    
    driveTrainRobotDrive41.reset(new RobotDrive(driveTrainLeftFront, driveTrainLeftBack,
              driveTrainRightFront, driveTrainRightBack));
    
    driveTrainRobotDrive41->SetSafetyEnabled(true);
        driveTrainRobotDrive41->SetExpiration(0.1);
        driveTrainRobotDrive41->SetSensitivity(0.5);
        driveTrainRobotDrive41->SetMaxOutput(1.0);

        driveTrainRobotDrive41->SetInvertedMotor(RobotDrive::kFrontRightMotor, true);
        driveTrainRobotDrive41->SetInvertedMotor(RobotDrive::kRearRightMotor, true);
    flapperFlapperMotor.reset(new CANTalon(12));
    lw->AddActuator("Flapper", "FlapperMotor", flapperFlapperMotor);
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
